# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Lessons/Architecture/task2/src/CPU.cache/wt [current_project]
set_property parent.project_path D:/Lessons/Architecture/task2/src/CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Lessons/Architecture/task2/src/CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs D:/Lessons/Architecture/task2/src/CPU.srcs [current_fileset]
read_mem D:/Lessons/Architecture/task2/src/CPU.srcs/sources/insts.mem
read_verilog -library xil_defaultlib {
  D:/Lessons/Architecture/task2/src/CPU.srcs/sources/def.v
  D:/Lessons/Architecture/task2/src/CPU.srcs/sources/cpu_controller.v
  D:/Lessons/Architecture/task2/src/CPU.srcs/sources/cpu_core.v
  D:/Lessons/Architecture/task2/src/CPU.srcs/sources/cpu_ex.v
  D:/Lessons/Architecture/task2/src/CPU.srcs/sources/cpu_id.v
  D:/Lessons/Architecture/task2/src/CPU.srcs/sources/cpu_if.v
  D:/Lessons/Architecture/task2/src/CPU.srcs/sources/cpu_mem.v
  D:/Lessons/Architecture/task2/src/CPU.srcs/sources/cpu_transmitter.v
  D:/Lessons/Architecture/task2/src/CPU.srcs/sources/fifo.v
  D:/Lessons/Architecture/task2/src/CPU.srcs/sources/memory_controller.v
  D:/Lessons/Architecture/task2/src/CPU.srcs/sources/mfifo.v
  D:/Lessons/Architecture/task2/src/CPU.srcs/sources/multchan_comm.v
  D:/Lessons/Architecture/task2/src/CPU.srcs/sources/reg_pc.v
  D:/Lessons/Architecture/task2/src/CPU.srcs/sources/regfile.v
  D:/Lessons/Architecture/task2/src/CPU.srcs/sources/uart_comm.v
  D:/Lessons/Architecture/task2/src/CPU.srcs/sources/top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top Top -part xc7a35ticpg236-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
